### PR TITLE
Release 0.0.5

### LINKED ISSUE #11: add an option to rollback all suggestions, i.e. "clear"

### LINKED ISSUE #20: Make configurations more useful
Currently a configuration has to overwrite all defaultConfiguration settings.

Configurations were supposed to only overwrite some properties, so if a property is changed in the default configuration, all configurations that do not overwrite that property will use the new value.

### LINKED ISSUE #27: single shared .discopop directory for both tools (hotspotdetection/discopop)

### LINKED ISSUE #40: revisit patch_applicator error logic
we should check if everything is implemented as intended (and correctly checked in the vs code gui)
https://github.com/discopop-project/discopop/pull/432

### LINKED ISSUE #42: Option to reset the directory upon request
If a configuration fails it is possible to end up in a state where no new run can be started, even if the underlying issue has been fixed. 
For me, this occurred when the installed DiscoPoP version did not match the required version.
For this reason, it would be nice to have the option to reset the state of a configuration to the vanilla state upon request.
This request could for example be implemented in the right-click-menu of the configuration.

A workaround for this is restarting visual studio code, which makes it not a high priority but a possible inconvenience.

### LINKED ISSUE #45: Show total amount of found suggestions

### LINKED ISSUE #46: Option to filter the suggestions tree: show applied/unapplied/all suggestion

### LINKED ISSUE #47: more intuitive loading of results / different configuration types
Loading of existing results currently requires creating an entire "cmake project configuration" and the results must be moved to very specific directories.

We should instead add a different configuration type, where the user only has to specify the path to the .discopop directory. This configuration can obviously not be executed, only loaded.

Optional: The user can specify a "run script" that runs discopop/hotspot detection. Then executing the configuration will launch that script.

### LINKED ISSUE #48: WithProgressRunner: normalize numbers

### PR DESCRIPTION
**Pull request by goerlibe**

### CODE REVIEW

**Comment by goerlibe** [comment]
bug: if a rollback is not changing anything, then the codelenses are not coming back (they are waiting for the lineMapping and appliedStatus files to be updated and will wait forever) --> ~simple solution: never wait for more than 5 seconds. Complex solution: observe if anything was rolled back, only then wait for the file updates. Medium Complex solution: make the "recomputing code lenses" notification cancellable and upon cancellation show the lenses again~ , better solution: #40 --> look for error codes to solve this

**Comment by goerlibe** [comment]
For now I "merged" the build directories, just for testing and making it work ASAP. It should be rather simple to continue this work, but I have to go :)

TODO:

- [ ] properly cleanup the .discopop directory when appropriate
- [x] use the environment variable DOT_DISCOPOP during the build process
- [x] separate build directories again

**Comment by goerlibe** [comment]
@lukasrothenberger not sure what I am doing wrong, but the explorer fails for me with this run process...
more specifically: in the FileMapping.txt some cmake temporary files are listed that no longer exist when the line_mapping is being initialized, which throws an error.

I am honestly lost and don't know what I am doing incorrectly. Any idea?

**Comment by lukasrothenberger** [comment]
Hi @goerlibe,
I've mentioned some hints to why this might happen in Element.
Nevertheless, i will make the import of the FileMapping.txt more robust. 
See https://github.com/discopop-project/discopop/issues/458.

**Comment by lukasrothenberger** [comment]
Hi @goerlibe,
please try it again using https://github.com/discopop-project/discopop/tree/458-filemapping-not-robust-wrt-deleted-files.

**Pull request merged**
